#! /bin/zsh -f

# mkvm_run ()
# {
(
  cd /scratch/sandbox;
  if [[ -e /scratch/sandbox/build-clone.qcow2 ]]; then
      rm -f /scratch/sandbox/build-clone.qcow2
  fi

  qemu-img create -b build/build.qcow2 -f qcow2 build-clone.qcow2

  export TMPDIR=/scratch/sandbox/tmp
  echo 'qemu-system-x86_64 -enable-kvm -snapshot -name build -hda build-clone.qcow2 '\\
  echo '      -m 512 -net tap,ifname=tap0,script=no,downscript=no   '\\
  echo '      -net nic,macaddr=$(printf "DE:AD:BE:EF:%02X:%02X\\n" $((RANDOM%256)) $((RANDOM%256)))'\\
  echo '      -serial telnet:localhost:7000,server,nowait,nodelay'\\
  echo '      -monitor telnet:localhost:7100,server,nowait,nodelay'\\
  echo '      -fsdev local,id=staging,path=/scratch/sandbox/staging,security_model=mapped-xattr'\\
  echo '      -device virtio-9p-pci,fsdev=staging,mount_tag=v_software'\\
  echo '      -display none'
  qemu-system-x86_64 -enable-kvm -snapshot -name build -hda build-clone.qcow2 \
                     -m 512 -net tap,ifname=tap0,script=no,downscript=no      \
                     -net nic,macaddr=$(printf 'DE:AD:BE:EF:%02X:%02X\n' $((RANDOM%256)) $((RANDOM%256))) \
                     -serial telnet:localhost:7000,server,nowait,nodelay      \
                     -monitor telnet:localhost:7100,server,nowait,nodelay     \
                     -fsdev local,id=staging,path=/scratch/sandbox/staging,security_model=mapped-xattr \
                     -device virtio-9p-pci,fsdev=staging,mount_tag=v_software \
                     -display none

# -net vde,sock=/var/run/vde2/mytap.ctl
# -net tap,ifname=build,script=no,downscript=no
# -net tap,ifname=tap0 -serial telnet:localhost:7000,server,nowait,nodelay \
# -monitor telnet:localhost:7100,server,nowait,nodelay -vnc :0"

#haltcmd="echo 'system_powerdown' | nc localhost 7100" # or netcat/ncat
)

# }
