#! /bin/zsh -f
#                               -*- Mode: Sh -*-
# options ---
# Author           : Manoj Srivastava ( srivasta@glaurung.internal.golden-gryphon.com )
# Created On       : Tue Jul 26 20:52:20 2005
# Created On Node  : glaurung.internal.golden-gryphon.com
# Last Modified By : Manoj Srivastava
# Last Modified On : Fri Apr 27 22:40:26 2007
# Last Machine Used: glaurung.internal.golden-gryphon.com
# Update Count     : 9
# Status           : Unknown, Use with caution!
# HISTORY          :
# Description      :
#
#

###
#Changing directories
###
setopt AUTO_CD
setopt AUTO_PUSHD
setopt CD_ABLE_VARS
setopt CDABLE_VARS
# don't push the same dir twice.
setopt PUSHD_IGNORE_DUPS
setopt PUSHD_TO_HOME
setopt NO_PUSHD_SILENT
setopt CHASE_DOTS
#setopt pushdminus
setopt NOHUP

# try to avoid the 'zsh: no matches found...'
setopt NONOMATCH

###
##Completion
###
#setopt alwaystoend
setopt ALWAYS_LAST_PROMPT
setopt ALWAYS_TO_END
setopt AUTO_LIST
setopt AUTO_MENU
setopt BASH_AUTO_LIST
setopt AUTO_NAME_DIRS

setopt AUTO_PARAM_KEYS
setopt AUTO_PARAM_SLASH

setopt AUTO_REMOVE_SLASH

#setopt complete_aliases
#setopt globcomplete

# Complete even when inside a word
setopt COMPLETE_IN_WORD

setopt LIST_AMBIGUOUS
setopt LIST_TYPES
setopt REC_EXACT
setopt HASH_LIST_ALL
# This is quite useful to avoid having to define extra completions for
# all your aliases. If you uncomment the line below, you'll have to
# define the completions separately for all your aliases.
# setopt COMPLETE_ALIASES

###
# expansion and globbing
###
setopt BAD_PATTERN
setopt EXTENDED_GLOB
setopt MARK_DIRS
setopt NO_MATCH
setopt NOMATCH
setopt CASE_GLOB
setopt CASE_MATCH
setopt EXTENDED_GLOB
# use zsh style word splitting
setopt NOSHWORDSPLIT

unsetopt GLOB_DOTS
# * shouldn't match dotfiles. ever.
setopt NOGLOBDOTS
setopt NO_GLOB_SUBST
setopt REMATCH_PCRE

#unsetopt EQUALS

#source ~/.zsh/options
###
## History
###
setopt APPEND_HISTORY
is4 && setopt SHARE_HISTORY
is4 && setopt histignorealldups
setopt INC_APPEND_HISTORY

setopt EXTENDED_HISTORY

setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_FIND_NO_DUPS

setopt HIST_ALLOW_CLOBBER
setopt HIST_REDUCE_BLANKS

setopt HIST_NO_STORE
setopt HIST_VERIFY

###
# Input/Output
###
setopt NO_CLOBBER
setopt CORRECT
setopt CORRECT_ALL
setopt MAIL_WARNING
#setopt PATH_DIRS
setopt RC_QUOTES
setopt PRINT_EXIT_VALUE
setopt RM_STAR_WAIT
setopt SHORT_LOOPS
setopt INTERACTIVE_COMMENTS
setopt HASH_CMDS
setopt HASH_DIRS
# Whenever a command completion is attempted, make sure the entire
# command path is hashed first.
setopt HASH_LIST_ALL

###
# Job Control
###
unsetopt BG_NICE
setopt AUTO_CONTINUE
setopt AUTO_RESUME
setopt CHECK_JOBS
setopt NOTIFY
setopt NO_HUP
setopt LONG_LIST_JOBS

###
# Scripts and Functions
###
setopt C_BASES
setopt MULTIOS

###
# ZLE
###
# avoid "beep"ing
# setopt NOBEEP
setopt BEEP
setopt EMACS

setopt FUNCTION_ARG_ZERO
#setopt KSH_AUTOLOAD

###
# Prompting
###
setopt PROMPT_SUBST
setopt PROMPT_BANG
setopt PROMPT_PERCENT

# make sure to use right prompt only when not running a command
is41 && setopt TRANSIENT_RPROMPT

# don't error out when unset parameters are used
setopt UNSET


# Local Variables:
# comment-start: "#"
# tab-width: 2
# mode: sh
# End:
