#! /bin/zsh -f
#                               -*- Mode: Sh -*- 
# variables --- 
# Author           : Manoj Srivastava ( srivasta@glaurung.internal.golden-gryphon.com ) 
# Created On       : Mon Aug  1 08:53:17 2005
# Created On Node  : glaurung.internal.golden-gryphon.com
# Last Modified By : Manoj Srivastava
# Last Modified On : Fri Sep 12 11:37:21 2008
# Last Machine Used: anzu.internal.golden-gryphon.com
# Update Count     : 36
# Status           : Unknown, Use with caution!
# HISTORY          : 
# Description      : 
# 
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
# Created On       : Mon Jul 25 15:18:23 2005
#
# Copyright © 2005-2010 Manoj Srivastava <srivasta@debian.org>

export DEBFULLNAME='Manoj Srivastava' 
export DEBEMAIL=srivasta@debian.org

# Local Variables: 
# comment-start: "#" 
# tab-width: 2 
# mode: sh
# End: 
