#! /bin/zsh -f
#                               -*- Mode: Sh -*-
# prompt ---
# Author           : Manoj Srivastava ( srivasta@glaurung.internal.golden-gryphon.com )
# Created On       : Wed Jul 27 08:54:21 2005
# Created On Node  : glaurung.internal.golden-gryphon.com
# Last Modified By : Manoj Srivastava
# Last Modified On : Tue May  6 23:00:03 2008
# Last Machine Used: anzu.internal.golden-gryphon.com
# Update Count     : 5
# Status           : Unknown, Use with caution!
# HISTORY          :
# Description      :
#
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# Copyright © 2005-2010 Manoj Srivastava <srivasta@debian.org>

# If running interactively, then:
if [[ -n "$PS1" ]]; then
    autoload -Uz vcs_info
    zstyle ':vcs_info:*' check-for-changes  true
    # The %F{n} enable ANSI color n for foreground, and %f disables
    # foreground color
    zstyle ':vcs_info:*' stagedstr 'S'
    zstyle ':vcs_info:*' unstagedstr 'D'
    zstyle ':vcs_info:*' actionformats \
           "%F{6}[${VCSH_REPO_NAME}${VCSH_REPO_NAME:+|}%b%F{2}|%F{1}%a%F{5}]_%c%u%f" \
           '%F{1}%F{5}(%f%s%F{5})%F{1}%r%f|%F{2}%S%f%m'
    zstyle ':vcs_info:*' formats \
           "%F{6}[${VCSH_REPO_NAME}${VCSH_REPO_NAME:+|}%b]_%c%u%f" \
           '%F{1}%F{5}(%f%s%F{5})%F{1}%r%f|%F{2}%S%f%m'
    zstyle ':vcs_info:(sv[nk]|bzr):*' branchformat '%b%F{1}:%F{3}%r'
    zstyle ':vcs_info:*' enable git cvs svn
    zstyle ':vcs_info:*' nvcsformats  "_"  "%f%1~"
    precmd () {
        vcs_info
        tracked=''
        if [[ $(git rev-parse --is-inside-work-tree 2> /dev/null) == 'true' ]] &&
           git status --porcelain | grep '??' &> /dev/null ; then
            #[[ -n $(git ls-files --others --exclude-standard) ]] ; then
            tracked="U"
        fi
    }
    autoload -U promptinit
    promptinit
    prompt manoj
fi

# Local Variables:
# comment-start: "#"
# tab-width: 2
# mode: sh
# End:
